apiVersion: "v1"
kind: "Service"
metadata:
  name: "{{ .Release.Name }}-kafka-svc"
  labels: &KafkaDeploymentLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: kafka
spec:
  type: "ClusterIP"
  ports:
    - port: 9092
      name: "kafka-port"
  selector: *KafkaDeploymentLabels
